FROM --platform=linux/amd64 ubuntu:24.04

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
      g++ make pkg-config autoconf \
      libsdl2-dev libgtk-3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . /src

RUN cd /src/SheepShaver && make links && \
    cd src/Unix && \
    autoheader && \
    ./configure --enable-sdl-video --enable-sdl-audio --enable-scsi-s2p --without-esd && \
    make -j$(nproc)
