FROM --platform=linux/amd64 ubuntu:24.04

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
      g++ make pkg-config autoconf \
      libsdl2-dev libgtk-3-dev \
      xvfb x11vnc fluxbox novnc websockify \
      curl net-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

EXPOSE 6080

CMD ["bash"]
